### PR TITLE
Crash when footer is not set

### PR DESCRIPTION
**Pull request by Ducatel**
Hi,

When you don't set the `footer` value in `encrypt` method call, a  `TypeError: can't concat str to bytes` is throw.

Reproduce it with
```python
from paseto import PasetoV2
import secrets

PasetoV2.encrypt(
        plaintext=b'mytext',
        key=secrets.token_bytes(32),
    )
```

### CODE REVIEW

**Comment by rlittlefield** [comment]
Good catch!

I'm trying to use a DCO for this. I know the change is small, but would you be willing to amend your commit (or squash) and add a Signed-off-by: <yourname> line to the commit message? I'm trying to make sure the provenance of all the commits is handled up front, and the DCO is handy for tracking these changes. Thanks! 😄 

https://github.com/rlittlefield/pypaseto/blob/master/CONTRIBUTING

**Comment by rlittlefield** [comment]
All tests are passing. Thanks for the contribution! 🎉 

Please let me know if you have any questions or concerns about the signed-off-by DCO stuff. 😄

**Comment by Ducatel** [comment]
Damn, I did theses quick commit directly on github and ...
 I didn't check the contributing guide, sorry my bad :bowtie:

For the DCO stuff, my commit is sign by PGP, it's enough ?
If not I will made the amend tomorrow :wink:

**Comment by rlittlefield** [comment]
The DCO requires the "Signed-off-by" as a way to acknowledge that your contribution is intentional and that you are allowed to do it, so the GPG signature is not enough. You can add the signed-off-by with  `git commit --amend --signoff` if that is easier than typing it.

**Comment by Ducatel** [comment]
For me signature is the best way to certify which my contribution is intentional.
I hope, I will never see my PGP signature on something I didn't do intentional  :stuck_out_tongue_closed_eyes:

I did the squash and the `Signed-off-by` ;)

**Pull request merged**
